In [1]:
import cycle_counting as cc
import csv
import torch
import math
import dgl
import numpy as np
import networkx as nx

Using backend: pytorch


Computing cycle homomorphism numbers and cycle isomorphism numbers in the nodes of the WL-indistinguishable CSL graphs 

In [2]:
import csv
with open('CSL_counts.csv', 'w', newline='') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=';',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerow(["Length n", "Skip lengths s ", "4 cycle hom", "6 cycle hom", "8 cycle hom", "10 cycle hom", "4 cycle sub", "6 cycle sub", "8 cycle sub", "10 cycle sub"])
    
for n in range(6,20):
    for s in range(2,n):
        print(n," skip ", s)
        graph = cc.generate_csl(n,s)
        hom_counts = cc.cycle_count_node_hom(graph)
        sub_counts = cc.cycle_count_node_sub(graph)
        print(hom_counts)
        print(sub_counts)
        with open('CSL_counts.csv', 'a', newline='') as csvfile:
            resultwriter = csv.writer(csvfile, delimiter=';',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
            resultwriter.writerow([n, s, hom_counts[1].item(), hom_counts[3].item(), hom_counts[5].item(), hom_counts[7].item(), sub_counts[1].item(), sub_counts[3].item(), sub_counts[5].item(), sub_counts[7].item()])

6  skip  2
tensor([     8,     48,    160,    704,   2688,  11008,  43520, 175104])
tensor([ 8, 20, 40, 32,  0,  0,  0,  0])
6  skip  3
tensor([    0,    27,     0,   243,     0,  2187,     0, 19683])
tensor([ 0, 12,  0, 12,  0,  0,  0,  0])
6  skip  4
tensor([     8,     48,    160,    704,   2688,  11008,  43520, 175104])
tensor([ 8, 20, 40, 32,  0,  0,  0,  0])
6  skip  5
tensor([  0,   6,   0,  22,   0,  86,   0, 342])
tensor([0, 0, 0, 2, 0, 0, 0, 0])
7  skip  2
tensor([     6,     44,    130,    622,   2258,   9548,  37032, 150734])
tensor([ 6, 16, 40, 60, 46,  0,  0,  0])
7  skip  3
tensor([     6,     44,    130,    622,   2258,   9548,  37032, 150734])
tensor([ 6, 16, 40, 60, 46,  0,  0,  0])
7  skip  4
tensor([     6,     44,    130,    622,   2258,   9548,  37032, 150734])
tensor([ 6, 16, 40, 60, 46,  0,  0,  0])
7  skip  5
tensor([     6,     44,    130,    622,   2258,   9548,  37032, 150734])
tensor([ 6, 16, 40, 60, 46,  0,  0,  0])
7  skip  6
tensor([  0,   6,   0,  20,  

Computing 4-cycle subgraph isomorphisms in the edges and in the nodes for the example graph from the paper

In [6]:
#Creating the graph

graph1 = cc.generate_csl(7,2)
graph2 = cc.generate_csl(7,3)
source = graph2.edges()[0].tolist()
dest = graph2.edges()[1].tolist()
source = [s+7 for s in source]
dest = [d+7 for d in dest]
graph1.add_nodes(7)
graph1.add_edges(source, dest)
source = [0,1,2,3,4,5,6]
dest = [7,8,9,10,11,12,13]
graph1.add_edges(source, dest)

#Node subgraph isomorphims are equal for node 0 and 7:

print(cc.cycle_count_node_sub(graph1, nodenum=0)[1])
print(cc.cycle_count_node_sub(graph1, nodenum=7)[1])

#While the sets of edge subgraph isomorphisms are not for this pair of nodes:

print(cc.number_of_squares_edge_sub(graph1,0,1), cc.number_of_squares_edge_sub(graph1, 0 ,2), cc.number_of_squares_edge_sub(graph1, 0 ,5), cc.number_of_squares_edge_sub(graph1, 0 ,6), cc.number_of_squares_edge_sub(graph1, 0 ,7))
print(cc.number_of_squares_edge_sub(graph1, 7 ,0), cc.number_of_squares_edge_sub(graph1, 7 ,8), cc.number_of_squares_edge_sub(graph1, 7 ,13), cc.number_of_squares_edge_sub(graph1, 7 ,10), cc.number_of_squares_edge_sub(graph1, 7 ,11))

tensor(20)
tensor(20)
4 5 5 4 2
2 6 6 3 3
